server:
  port: 8762

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: mall-order

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/