server:
  port: 8782

spring:
  application:
    name: mall-order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mq:
  config:
    exchange: log.direct
    queue:
      info:
        routing:
          key: log.info.routing.key
      error:
        routing:
          key: log.error.routing.key