server:
  port: 8772

spring:
  application:
    name: mall-user
  ## 数据源配置
  datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

service:
  url:
    order: mall-order


# mybatis
mybatis:
  type-aliases-package: com.policeschool.mall.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true