server:
  port: 9000

spring:
  application:
    name: service-zuul
  redis:
      host: 127.0.0.1
      database: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    order:
      path: /order/**
      service-id: mall-order
    user:
      path: /user/**
      service-id: mall-user
    product:
          path: /product/**
          service-id: mall-product
    order-log:
      path: /order-log/**
      service-id: order-log