server:
  port: 8792

spring:
  application:
    name: order-log
  rabbitmq:
      host: 47.107.94.174
      port: 5672
      username: guest
      password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# https://www.cnblogs.com/jing99/p/11679426.html
mq:
  config:
    exchange: log.direct
    queue:
      info:
        routing:
          key: log.info.routing.key
      error:
        routing:
          key: log.error.routing.key