server:
  port: 8761
#  port: 8762

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8762/eureka/
##      defaultZone: http://${eureka.instance.hostname}:8761/eureka/